[tools]
bazel = "latest"
elixir = "latest"
erlang = "latest"
gleam = "latest"
lua = "latest"
neovim = "nightly"
nodejs = "latest"
rebar = "latest"
rust = "nightly"
zig = "latest"
bun = "latest"
go = "latest"
pnpm = "latest"
stylua = "latest"
